name: Create Release for Main

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: lincheoll/test-workflows/.github/workflows/release-main.yml@main
    with:
      node_version: '22'
    secrets: inherit