name: Create Pre-Release for Staging

on:
  push:
    branches:
      - staging

jobs:
  release:
    uses: lincheoll/test-workflows/.github/workflows/release-staging.yml@main
    with:
      node_version: '22'
    secrets: inherit